MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: 'C:/Users/laobo/.cache/torch/checkpoints/resnet50-19c8e357.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'no'
  IF_WITH_CENTER: 'no'
  NECK: 'no'



INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('Market1501_multi_camera')

DATALOADER:
  SAMPLER: 'softmax_multi_camera'
  NUM_CAMERA: 6
  NUM_INSTANCE: 2
  NUM_IDS: 6
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 72

  STEPS: [30, 55]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 20
  LOG_PERIOD: 20
  EVAL_PERIOD: 20

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'no'
  WEIGHT: "path"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'